settings:
  react:
    version: detect
env:
  browser: true
  es6: true
  jest: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:jest/recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
    modules: true
  sourceType: module
plugins:
  - react
  - react-hooks
  - '@typescript-eslint'
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  react-hooks/rules-of-hooks:
    - error
  react-hooks/exhaustive-deps:
    - warn
  '@typescript-eslint/no-explicit-any':
    - off
  '@typescript-eslint/explicit-function-return-type':
    - off
